In [1]:
from MTW.mtw_gravitation import *

g = Metric()
u = np.array([1.0, 0.0, 0.0, 1.0])
v = np.array([1.0, 1.0, 1.0, 0.0])
xi = v - u
print(g.eta)
print(g.scalar_product(xi, xi))

print(f'Mass of sun = {M_Sun*GRAM_PER_KG}g = {M_Sun}kg')
print(f'= {M_Sun*M_PER_KG*CM_PER_M}cm')

[[-1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
3.0
Mass of sun = 1.989e+33g = 1.9890000000000002e+30kg
= 147683.25000000003cm


Coordinates of an event P are denoted by (x0, x1, x2, x3)
x_mu(P) or x_alpha(P), ie a Greek index, denotes values 0, 1, 2, 3
Space coordinates, (x1, x2, x3), are denoted by a Latin index, x_j or x_j, taking on values 1, 2, 3

Other coordinates for the same event are noted with a bar, hat, or prime

    x_alpha_bar(P)

Separation vector is denoted xi,

    xi = P - Q 
    
in flat spacetime (aka vector from Q to P)

Transformation of components of a vector from one coordinate system to another is achieved by partial derivatives of transformation equations

    xi_alpha_bar = (dx_alpha_bar / dx_beta) xi_beta

Einstein summation convention:
any index repeated in a product is summed over

    (dx_alpha_bar / dx_beta) xi_beta == sum(beta = 0:3) (dx_alpha_bar / dx_beta) xi_beta

Local Lorentz Geometry:
(language of coordinates)

From any event A to any other nearby event B, there is a proper distance s_AB or proper time tau_AB given in suitable (local Lorentz) coordinates by

s_AB^2 = -tau_AB^2 =   -[x0(B) - x0(A)]^2
                        [x1(B) - x1(A)]^2
                        [x2(B) - x2(A)]^2
                        [x3(B) - x3(A)]^2

If this is locally true for all neighboring events A and B, then
(i) this coordinate system is locally Lorentzian
(ii) the geometry of spacetime is locally Lorentzian

At each point of any Riemannian manifold, there exists a geometrical object called the metric tensor, g.

g(u, u) = u^2, the square of the length of u
g(u, v) = u dot v, the scalar product of u on v

The operation of the metric tensor is
g(u, v) = g_alpha_beta * u_alpha * v_beta (implied summation on alpha, beta)

In local Lorentz coordinates, the components of g are

                        --Beta-->

eta_alpha_beta =   |    |-1 0 0 0|
                 alpha  | 0 1 0 0|
                   |    | 0 0 1 0|
                   V    | 0 0 0 1|

The Riemann curvature tensor, R, takes 3 4-vectors as inputs and returns a 4-vector

Choose a fiducial geodesic (free-particle world line) passing through event Q, and denote its unit tangent vector (particle 4-velocity) there by

    u = dx/dtau; components u_alpha = dx_alpha / dtau
    (tau = proper time)

Choose another, neighboring geodesic, and denote by xi its perpendicular separation from the fiducial geodesic. Then insert u into the first and third slots, and xi into the second:

    r = Riemann(u, xi, u)

The equation of geodesic deviation states that the result of the Riemann tensor's calculation is a vector which is the negative of the relative acceleration of the two geodesics:

    d2xi_dtau2 + Riemann(u, xi, u) = 0

In any coordinate system the components of the output vector can be written as a linear function of the input components:

    r = Riemann(u, v, w) = r_alpha = R_alpha_beta_gamma_delta * u_beta * v_gamma * w_delta (implied summation on beta, gamma, delta)

    R_alpha_beta_gamma_delta = 4x4x4x4 = 256 numbers, the components of the Riemann tensor in the given coordinate system

In terms of components, the equation of geodesic deviation states

    d2xi_alpha/dtau2 + R_alpha_beta_gamma_delta * dx_beta/dtau * xi_gamma * dx_delta/dtau

In Einstein's geometric theory of gravity, this equation of geodesic deviation summarizes the entire effect of geometry on matter.

Consider the separation between two geodesics of two nearby and slowly moving (v << c) particles at a distance r from the Earth or sun. In the standard, nearly inertial coordinates of celestial mechanics, all components of the 4-velocity of the fiducial test particle can be neglected except dx0/dtau = 1. The space components of the equation of geodesic deviation read

    d2xi_k/dtau2 + R_k_0j0 * xi_j = 0

Then the Riemann tensor in Newtonian theory is

|R_xhat_0xhat0 R_yhat_0xhat0 R_zhat_0xhat0|   |m/r^3 0      0     |
|R_xhat_0yhat0 R_yhat_0yhat0 R_zhat_0yhat0| = |0     m/r^3  0     |
|R_xhat_0zhat0 R_yhat_0zhat0 R_zhat_0zhat0|   |0     0     -2m/r^3|

The Einstein tensor, G, is always generated directly by the local distribution of matter.
It is the geometric object that generalizes the trace of the Riemann curvature tensor.

Generating Einstein is a geometric object called the stress-energy tensor of the matter, T.

    G = 8pi * T

This is the Einstein Field Equation. Rewritten in arbitrary coordinates, it reads

    G_alpha_beta = 8 * pi * T_alpha_beta

In [2]:
# Exercises

# 1.1 CURVATURE OF A CYLINDER

In [3]:
# 1.2 SPRING TIDE VS NEAP TIDE

# Evaluate the magnitude of Newtonian tide-producing acceleration generated at the earth by

# 1. The Moon
m_moon = 7.35e25 * KG_PER_GRAM # mass of the moon
r_moon = 3.84e10 * M_PER_CM # distance of the moon from Earth
R_moon = Riemann_Newton(m_moon, r_moon)
print(f'Moon: R (kg/m^3) = \n{R_moon}')

# 2. The Sun
m_sun = 1.989e33 * KG_PER_GRAM # mass of the Sun
r_sun = 1.496e13 * M_PER_CM # distance of the sun from Earth
R_sun = Riemann_Newton(m_sun, r_sun)
print(f'Sun: R (kg/m^3) = \n{R_sun}')

# By what factor do spring tides exceed neap?
# spring tide: moon & sun aligned
# neap tide: moon & sun 90 deg offset
spring = R_sun[0,0] + R_moon[0,0]
neap = R_moon[0,0] - R_sun[0,0]
print(f'spring tides exceed neap by a factor of {spring/neap}')

Moon: R (kg/m^3) = 
[[ 0.00129806  0.          0.        ]
 [ 0.          0.00129806  0.        ]
 [ 0.          0.         -0.00259611]]
Sun: R (kg/m^3) = 
[[ 0.00059407  0.          0.        ]
 [ 0.          0.00059407  0.        ]
 [ 0.          0.         -0.00118815]]
spring tides exceed neap by a factor of 2.687747789963232


In [4]:
# 1.3 KEPLER ENCAPSULATED