In [ ]:
from MTW.mtw_gravitation import *

In flat space, a vector from event A to event B is

    v_AB = B - A

In curved space, define the concept of a tangent vector at point P:

    v_AB = (dP/dlambda)|lambda=0

If P(tau) is a straight world line, then the displacement in a proper time interval of one second is

    u = P(1) - P(0)     <--This is the 4-velocity

Given a world line P(tau) that is not straight, first form

    u = dP/dtau

and then draw the straight line

    P(0) + lambda(dP/dtau)|0

to display the 4-velocity

In a Lorentz reference frame, the 4-velocity has components

    u0 = dt/dtau = 1 / sqrt(1 - v^2)
    uj = dxj/dtau = vj / sqrt(1 - v^2)

where
    vj = dxj/dt = components of "ordinary velocity", which is normalized by c to be unitless, ie v/c
    v^2 = vx^2 + vy^2 + vz^2


Coordinates enter the picture when analysis on a computer is required. For this purpose, adopt a Lorentz frame with orthonormal basis vectors

    e0, e1, e2, e3

Relative to the origin O of this frame, the world line has description

    P(tau) - O  = x0(tau)*e0 + x1(tau)*e1 + x2(tau)*e2 x3(tau)*e3
                = x_mu(tau) * e_mu

Expressed relative to the same Lorentz frame, the 4-velocity of the particle is

    u = dP/dtau = (dx_mu/dtau)*e_mu
                = u0*e0 + u1*e1 + u2*e2 + e3*e3

In [2]:
# Lorentz frame 4-velocity
g = Lorentz_Metric()

# geometrized "ordinary velocity", unitless, aka rapidity
vlist = [ np.array([1.0, 0.0, 0.0]) / c,
          np.array([1000.0, 0.0, 0.0]) / c,
          np.array([0.1, 0.0, 0.0]),
          np.array([0.25, 0.0, 0.0]),
          np.array([0.5, 0.0, 0.0]),
          np.array([0.9, 0.0, 0.0])
        ]

for v in vlist:
    u = four_velocity(v)
    print(f'given ordinary velocity vj = {v} c,\nthe corresponding 4-velocity u = \n{u}')
    print(f'which has 2-norm {np.linalg.norm(u)} and metric length {g.scalar_product(u,u)}')


given ordinary velocity vj = [3.33563492e-09 0.00000000e+00 0.00000000e+00] c,
the corresponding 4-velocity u = 
[[1.00000000e+00]
 [3.33563492e-09]
 [0.00000000e+00]
 [0.00000000e+00]]
which has 2-norm 1.0 and metric length [-1.]
given ordinary velocity vj = [3.33563492e-06 0.00000000e+00 0.00000000e+00] c,
the corresponding 4-velocity u = 
[[1.00000000e+00]
 [3.33563492e-06]
 [0.00000000e+00]
 [0.00000000e+00]]
which has 2-norm 1.0000000000111264 and metric length [-1.]
given ordinary velocity vj = [0.1 0.  0. ] c,
the corresponding 4-velocity u = 
[[1.00503782]
 [0.10050378]
 [0.        ]
 [0.        ]]
which has 2-norm 1.0100505037878158 and metric length [-1.]
given ordinary velocity vj = [0.25 0.   0.  ] c,
the corresponding 4-velocity u = 
[[1.03279556]
 [0.25819889]
 [0.        ]
 [0.        ]]
which has 2-norm 1.064581294844754 and metric length [-1.]
given ordinary velocity vj = [0.5 0.  0. ] c,
the corresponding 4-velocity u = 
[[1.15470054]
 [0.57735027]
 [0.        ]
 [0. 

In [3]:
# Metric tensor in a Lorentz frame:

# Basis vectors
e0 = np.array([1.0, 0.0, 0.0, 0.0])
e1 = np.array([0.0, 1.0, 0.0, 0.0])
e2 = np.array([0.0, 0.0, 1.0, 0.0])
e3 = np.array([0.0, 0.0, 0.0, 1.0])

g = Lorentz_Metric()

u = np.array([0., 1., 0., 2.])
v = np.array([0., 1., 1., 0.])
print(f'u dot v = {g.scalar_product(u, v)} (positive -> spacelike)')

u = np.array([1., 0., 0., 0.])
v = np.array([2., 0., 0., 0.])
print(f'u dot v = {g.scalar_product(u, v)} (negative -> timelike)')

u = np.array([0., 0., 0., 0.])
v = np.array([1., 1., 0., 0.])
print(f'u dot v = {g.scalar_product(u, v)} (zero -> null or lightlike)')

u dot v = 1.0 (positive -> spacelike)
u dot v = -2.0 (negative -> timelike)
u dot v = 0.0 (zero -> null or lightlike)


Box 2.2 

Let the special relativistic correction factor equal gamma:

    gamma = 1 / (1 - v^2)

Exercise 1
Show that the squared length of a test particle's 4-velocity u is -1

    u^2 = g(u,u) = -gamma + gamma*v^2 = -1

Exercise 2
Show that the rest mass of a particle is related to its energy and momentum by the famous equation

    (mc^2)^2 = E^2 - (pc^2)

or in geometrized units

    m^2 = E^2 - p^2

Solution

    E^2 = gamma * m^2
    p^2 = gamma * m^2 * v^2

In [4]:
v = np.array([0.1, 0.0, 0.0])
m = 2 # rest mass, kg

u = four_velocity(v)
p = four_momentum(u, m)
print(f'given ordinary velocity vj = {v} c,\nthe corresponding 4-velocity u = \n{u}')
print(f'which has metric length {g.scalar_product(u,u)}')
print(f'with a rest mass of {m} kg, the 4-momentum p = \n{p}')
print(f'which has metric length {g.scalar_product(p,p)} = -m^2')

# Box 2.2 Exercise 2

print(f'relativistic momentum p = {relativistic_momentum(v, m)}')
print(f'relativistic energy E = {mv_to_E(v, m)}')
print(f'relativistic energy E (alt calc) = {p_to_E(v, m)}')
print(f'm^2 = {g.scalar_product(p,p)}')
print(f'E^2 - p^2 = {mv_to_E(v, m)**2 - relativistic_momentum(v, m)**2}')

given ordinary velocity vj = [0.1 0.  0. ] c,
the corresponding 4-velocity u = 
[[1.00503782]
 [0.10050378]
 [0.        ]
 [0.        ]]
which has metric length [-1.]
with a rest mass of 2 kg, the 4-momentum p = 
[[2.01007563]
 [0.20100756]
 [0.        ]
 [0.        ]]
which has metric length [-4.] = -m^2
relativistic momentum p = 0.19949811398673623
relativistic energy E = 2.005031486295626
relativistic energy E (alt calc) = 1.79751685698e+17
m^2 = [-4.]
E^2 - p^2 = 3.9803517635525836


Differential Forms, aka 1-Forms

1-Forms are sometimes denoted as Latin letters with tildes (k~) but more often by boldface Greek letters (alpha, beta)

View a 1-form as a family of flat, equally spaced surfaces. Take two nearby points, P and P0. Run an arrow v = P - P0 from P0 to P. It will pierce a certain number of surfaces of integral phase. The number of surfaces pierced is denoted

    <k~, v>

where k~ is the 1-form being pierced and v is the vector that pierces. This is read as "the contraction of k~ with v" or "the value of k~ on v."

Regard the 1-form k~ as a machine into which vectors are inserted, and from which numbers emerge. Normally neither P0 nor P will lie at a point of integral phase, and the precise result is interpolated.

Mathematical definition: a 1-form is a lienar, real-valued function of vectors. The set of all 1-forms at a given event is a "vector space."

Correspondence between 1-forms and vectors:

    p dot v = <p~, v>   (2.14)

In words: the projection of v on the 4-momentum vector p equals the number of surfaces it pierces in the 4-momentum 1-form p~.
Corresponding to any vector p there exists a unique 1-form (linear function of vectors) p~ defined by (2.14)

Coordinate representation:
The components u_alpha of the 1-form u~ that corresponds to a vector u can be obtained by "lowering an index" with the metric coefficients eta_alpha_beta:

    u_alpha = eta_alpha_beta * u^beta, ie
    u_0 = -u^0, u_k = u^k

eta^alpha^beta, the inverse of eta_alpha_beta, is equal to eta_alpha_beta
therefore, in component form, lowering an index to convert a vector to a 1-form
is exactly the same operation as raising an index to convert a 1-form to a vector